version: "3.1"
services:
  db:
    image: postgis/postgis:15-3.5
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./raw_data/sprint2_dump.sql:/sprint2_dump.sql
#      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    env_file:
      - ./db.env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - ./pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./raw_data/practicum_sql_for_dev_project_3.sql:/var/lib/pgadmin/storage/user-name_domain-name.com/practicum_sql_for_dev_project_3.sql
    depends_on:
      - db

volumes:
  local_pgdata:
  pgadmin-data: